### PR TITLE
🐛 fix: Abnormal animation of tokens

### LINKED ISSUE #10095: [Bug] Abnormal animation when switching token usage units
### 📱 Client Type

Web (Desktop Browser)

### 💻 Operating System

macOS

### 📦 Deployment Platform

Self hosting Docker

### 🔧 Deployment Mode

server db (lobe-chat-database image)

### 📌 Version

v2.0.0-next.36

### 🌐 Browser

Other

### 🐛 Bug Description

https://github.com/user-attachments/assets/4a91a710-675b-4237-af81-01b389282dcb

ref: https://discord.com/channels/1127171173982154893/1174664494883016804/1436286703492010116

### 📷 Recurrence Steps

_No response_

### 🚦 Expected Behavior

_No response_

### 📝 Additional Information

_No response_

### 🛠️ Willing to Submit a PR?

None

### ✅ Validations

- [x] Read the [docs](https://lobehub.com/zh/docs).
- [x] Check that there isn't [already an issue](https://github.com/lobehub/lobe-chat/issues) that reports the same bug to avoid creating a duplicate.
- [x] Make sure this is a LobeChat issue and not a third-party library or provider issue.
- [x] Check that this is a concrete bug. For Q&A, please use [GitHub Discussions](https://github.com/lobehub/lobe-chat/discussions) or join our [Discord Server](https://discord.gg/rGHwKq4R).

---
> This issue was translated by Claude.

<details>
<summary>Original Content</summary>

**Title:** [Bug] 切换 token 用量计量单位时出现异常动画

**Body:**
### 📱 Client Type

Web (Desktop Browser)

### 💻 Operating System

macOS

### 📦 Deployment Platform

Self hosting Docker

### 🔧 Deployment Mode

server db (lobe-chat-database image)

### 📌 Version

v2.0.0-next.36

### 🌐 Browser

Other

### 🐛 Bug Description

https://github.com/user-attachments/assets/4a91a710-675b-4237-af81-01b389282dcb

ref: https://discord.com/channels/1127171173982154893/1174664494883016804/1436286703492010116

### 📷 Recurrence Steps

_No response_

### 🚦 Expected Behavior

_No response_

### 📝 Additional Information

_No response_

### 🛠️ Willing to Submit a PR?

None

### ✅ Validations

- [x] Read the [docs](https://lobehub.com/zh/docs).
- [x] Check that there isn't [already an issue](https://github.com/lobehub/lobe-chat/issues) that reports the same bug to avoid creating a duplicate.
- [x] Make sure this is a LobeChat issue and not a third-party library or provider issue.
- [x] Check that this is a concrete bug. For Q&A, please use [GitHub Discussions](https://github.com/lobehub/lobe-chat/discussions) or join our [Discord Server](https://discord.gg/rGHwKq4R).
</details>

### PR DESCRIPTION
**Pull request by sxjeru**
#### 💻 Change Type

- [ ] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 👷 build
- [ ] ⚡️ perf
- [ ] ✅ test
- [ ] 📝 docs
- [ ] 🔨 chore

#### 🔗 Related Issue

- fix #10095

#### 🔀 Description of Change

四舍五入数字渐变的过程，避免小数。

另支持点击 tokens 数在长短格式间转换。11.1k <-> 11,100

#### 🧪 How to Test

- [x] Tested locally
- [ ] Added/updated tests
- [ ] No tests needed

#### 📸 Screenshots / Videos

| Before | After |
| ------ | ----- |
| ...    | ...   |

## Summary by Sourcery

Round animated number values to integers to avoid decimal artifacts and add click handling to toggle between shortened and full number formats.

New Features:
- Add click-to-toggle functionality to switch between short and full numeric display formats

Bug Fixes:
- Round numbers during animation to prevent abnormal decimal transitions

### CODE REVIEW

File: src/features/Conversation/components/Extras/Usage/UsageDetail/index.tsx [hunk 1]
```diff
@@ -24,9 +25,26 @@ interface TokenDetailProps {
...
 
+const STORAGE_KEY = 'lobe-chat-token-display-format';
+
 const TokenDetail = memo<TokenDetailProps>(({ meta, model, provider }) => {
   const { t } = useTranslation('chat');
   const theme = useTheme();
+  const isMobile = useIsMobile();
+
+  // 从 localStorage 读取初始值，默认为 true (短格式)
+  const [isShortFormat, setIsShortFormat] = useState(() => {
```
Comment (arvinxx) [inline src/features/Conversation/components/Extras/Usage/UsageDetail/index.tsx]: localStorage 要用 systemStatus

**Review by arvinxx — COMMENTED** [review]
录个屏看下？

**Comment by sxjeru** [comment]
https://github.com/user-attachments/assets/bd56819c-ca38-499b-afa1-c49037301066

**Comment by AnotiaWang** [comment]
I feel that this animation is still a bit sluggish; it might be more crisp without animation.

---
> This comment was translated by Claude.

<details>
<summary>Original Content</summary>
感觉这个动画还是有点拖沓了,无动画可能更干脆些
</details>

**Comment by arvinxx** [comment]
@sxjeru How about setting the speed to 1.5s?

---
> This comment was translated by Claude.

<details>
<summary>Original Content</summary>
@sxjeru 速度要不设成 1.5s 吧
</details>

File: src/features/Conversation/components/Extras/Usage/UsageDetail/index.tsx [hunk 2]
```diff
@@ -211,15 +217,32 @@ const TokenDetail = memo<TokenDetailProps>(({ meta, model, provider }) => {
...
+          updateSystemStatus({ tokenDisplayFormatShort: !isShortFormat });
+        }}
+        style={{ cursor: isMobile ? 'default' : 'pointer' }}
+      >
         <Icon icon={isShowCredit ? BadgeCent : CoinsIcon} />
         <AnimatedNumber
-          formatter={(value) => (formatShortenNumber(value) as string).toLowerCase?.()}
-          // Force remount when switching between token/credit to prevent unwanted animation
-          // See: https://github.com/lobehub/lobe-chat/pull/10098
-          key={isShowCredit ? 'credit' : 'token'}
```
Comment (arvinxx) [inline src/features/Conversation/components/Extras/Usage/UsageDetail/index.tsx:222]: @sxjeru key 仍然要保留的吧？

Comment (sxjeru) [reply src/features/Conversation/components/Extras/Usage/UsageDetail/index.tsx:222]: 加 key 的话切换价格就没有动画了，这是预期的吗？
