### PR TITLE
🐛 fix: fix the artifacts interface not scrolling

### LINKED ISSUE #4425: [Bug] Artifacts预览模式 显示不完整
### 📦 Environment

Docker

### 📌 Version

v1.22.10

### 💻 Operating System

Windows

### 🌐 Browser

Chrome

### 🐛 Bug Description

Artifacts生成的结果，代码视图下，能够通过上下滚动看到全部生成内容。
当切换到预览视图下，无法上下滚动，此时只能看到部分预览内容。

图1 代码视图
Screenshot 2024-10-20 153216

图2 预览视图（仅显示前部分内容）
Screenshot 2024-10-20 153202

### 📷 Recurrence Steps

_No response_

### 🚦 Expected Behavior

能够通过上下滚动，浏览全部Artifacts预览内容。

### 📝 Additional Information

_No response_

### PR DESCRIPTION
**Pull request by mushan0x0**
#### 💻 变更类型 | Change Type

- [ ] ✨ feat
- [x] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 👷 build
- [ ] ⚡️ perf
- [ ] 📝 docs
- [ ] 🔨 chore

#### 🔀 变更说明 | Description of Change

close: #4425

Markdown 修改后可以滚动

image

插件之前也有点问题，不能滚动，看不到下面创建消息栏

image

插件修改后

image

### CODE REVIEW

File: src/app/(main)/chat/(workspace)/@portal/features/Body.tsx [hunk 1]
```diff
@@ -16,7 +16,7 @@ const Body = ({ children }: PropsWithChildren) => {
     <Flexbox
       className={cx(body, 'portal-body')}
       height={'100%'}
-      style={{ position: 'relative' }}
+      style={{ flex: 1, height: 0, position: 'relative' }}
```
Comment (arvinxx) [inline src/app/(main)/chat/(workspace)/@portal/features/Body.tsx:19]: 这里为啥要加 height:0

Comment (mushan0x0) [reply src/app/(main)/chat/(workspace)/@portal/features/Body.tsx:19]: 让 flex: 1 生效，不然自动高度大于 flex: 1 的高度时 flex 不会生效


https://github.com/user-attachments/assets/4f24a002-d4b9-4a6a-8dc6-49fb4ec5c3fb

**Comment by ChenglongWang** [comment]
This bug is really annoying, please merge this PR ASAP. Thanks!
