### PR TITLE
💄 style: support ContextMenu on ChatItem

### LINKED ISSUE #1920: [Request] Right-click menu support
### 🥰 需求描述

使得有菜单的按钮等控件右击时显示其菜单，而不是浏览器的菜单

### 🧐 解决方案

使得有菜单的按钮等控件右击时显示其菜单，而不是浏览器的菜单

### 📝 补充信息

_No response_

### LINKED ISSUE #8463: Missing context menu for text selection
### 📦 Platform

Official Preview

### 📦 Deploymenet mode

client db (lobe-chat image)

### 📌 Version

v1.99.6

### 💻 Operating System

Windows

### 🌐 Browser

Other

### 🐛 Bug Description

Right-clicking on selected text in LobeHub does not display a context menu, making it impossible to copy text using the standard right-click → copy workflow.

### 📷 Recurrence Steps

1. Open LobeHub desktop application
2. Select any text in a conversation (user message or AI response)
3. Right-click on the selected text
4. No context menu appears

### 🚦 Expected Behavior

A context menu should appear when right-clicking selected text, containing at least Copy, Select All, and other standard text operations.

### 📝 Additional Information

OS: Windows 11 24H2
Installation Method: Desktop App
This is a basic UI/UX feature that users expect in desktop applications. Currently, users must use keyboard shortcuts (Ctrl+C) which may not be intuitive for all users

### LINKED ISSUE #9262: [Desktop] Right-click menu copy not working
### 📦 部署环境

Official Cloud

### 📦 部署模式

服务端模式(lobe-chat-database 镜像)

### 📌 软件版本

latest

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome

### 🐛 问题描述

1.桌面端右击菜单复制失效，若右击时正好选中了文本则复制成功
2.桌面端右击select all，默认会把应用内所有文本都选中，期望选中对话框内文本

### 📷 复现步骤

_No response_

### 🚦 期望结果

_No response_

### 📝 补充信息

_No response_

### PR DESCRIPTION
**Pull request by ONLY-yours**
#### 💻 变更类型 | Change Type

Ref：
https://github.com/lobehub/lobe-chat/discussions/8442
- close https://github.com/lobehub/lobe-chat/issues/8463
- close https://github.com/lobehub/lobe-chat/issues/9262
- close https://github.com/lobehub/lobe-chat/issues/1920

- [x] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [x] 💄 style
- [ ] 👷 build
- [ ] ⚡️ perf
- [ ] ✅ test
- [ ] 📝 docs
- [ ] 🔨 chore

## Summary by Sourcery

Support fast invocation of a desktop context menu on each chat message by right-clicking, replacing the previous Electron-based menu with a custom React-driven menu that offers common chat actions and a share modal.

New Features:
- Add right-click context menu on chat items with custom actions (copy, edit, translate, TTS, regenerate, share, delete, etc.)
- Implement useChatItemContextMenu hook to manage context menu triggering, positioning, and closing
- Introduce ContextMenu component and integrate it into ChatItem along with a ShareMessageModal
- Add a CSS class to message content elements for accurate context menu target detection

### CODE REVIEW

**Comment by arvinxx** [comment]
image

这个控制区间不够精准，另外我比较 concern 原本的这种功能就没了

image

**Comment by ONLY-yours** [comment]
区域现在仅限于 ChatItem Markdown 的内容区，需要调整到整行还是整个 ChatItem 

@arvinxx 因为相当于要阻止默认的右键了，浏览器上是会少几个功能，但是在桌面端体验就会好很多

或者我们把右键这个能力单独做到桌面端？在浏览器中不打开呢？

**Comment by ONLY-yours** [comment]
> 这个控制区间不够精准，另外我比较 concern 原本的这种功能就没了

控制区间更新了，现在是标准的对话区域了

原本浏览器的右键功能，现在在 settings 增加了一个功能，桌面端默认用写好的 ContextMenu ，网页版本默认不使用，可以自己打开 / 关闭进行配置 

@arvinxx

**Comment by arvinxx** [comment]
@ONLY-yours Need to rebase?

---
> This comment was translated by Claude.

<details>
<summary>Original Content</summary>

@ONLY-yours 需要 rebase ?
</details>

**Comment by arvinxx** [comment]
@ONLY-yours rebase?

---
> This comment was translated by Claude.

<details>
<summary>Original Content</summary>

@ONLY-yours rebase 下?
</details>

File: src/locales/default/setting.ts [hunk 1]
```diff
@@ -204,6 +204,12 @@ export default {
       elegant: '优雅',
       title: '响应动画',
     },
+    contextMenuMode: {
+      default: 'LobeChat默认',
```
Comment (arvinxx) [inline src/locales/default/setting.ts]: Just call it 'Default'

---
> This comment was translated by Claude.

<details>
<summary>Original Content</summary>
就叫默认
</details>

File: src/features/Conversation/Messages/index.tsx [hunk 2]
```diff
@@ -53,11 +66,295 @@ const Item = memo<ChatListItemProps>(
...
+    const intersectionRef = useRef<HTMLDivElement | null>(null);
+    const { message } = App.useApp();
+    const { t } = useTranslation('common');
+    const searchParams = useSearchParams();
 
     const item = useChatStore(chatSelectors.getMessageById(id), isEqual);
 
     const [isMessageLoading] = useChatStore((s) => [chatSelectors.isMessageLoading(id)(s)]);
+    const editing = useChatStore((s) => chatSelectors.isMessageEditing(id)(s));
+    const [
```
Comment (arvinxx) [inline src/features/Conversation/Messages/index.tsx]: I feel this implementation shouldn't be placed directly here? It should be extracted into a sub-component instead, right?

---
> This comment was translated by Claude.

<details>
<summary>Original Content</summary>
我感觉这段实现不应该直接放在这里?应该抽一个子组件放进去才对吧
</details>

File: src/features/ChatList/Messages/Assistant/Actions/index.tsx
Comment (arvinxx) [inline src/features/ChatList/Messages/Assistant/Actions/index.tsx:1]: Why does this need to be changed to onShare?

---
> This comment was translated by Claude.

<details>
<summary>Original Content</summary>
为啥这里要改成onShare
</details>

**Review by arvinxx — CHANGES_REQUESTED** [review]

**Comment by arvinxx** [comment]
@ONLY-yours rebase 下，这个没处理
