### PR TITLE
🐛 fix: type not preserved when model batch processing

### LINKED ISSUE #10522: With the entire model list disabled, all models became dialogue models, and image models were no longer suitable for AI painting.
### 📱 Client Type

Web (Desktop Browser)

### 💻 Operating System

macOS

### 📦 Deployment Platform

Self hosting Docker

### 🔧 Deployment Mode

server db (lobe-chat-database image)

### 📌 Version

1.143.0

### 🌐 Browser

Chrome

### 🐛 Bug Description

As you can see, by default, Volcengine has three image generation models.

Image

When I clicked "Disable All," all models became dialogue models.

Image

Image

At this point, when I use AI painting, even though my Seedream 4.0 model is enabled, there are no models in the AI ​​painting model list.

Image

After I clicked the "Reset All Changes" button, it was restored.

Image

Image

### 📷 Recurrence Steps

_No response_

### 🚦 Expected Behavior

_No response_

### 📝 Additional Information

_No response_

### 🛠️ Willing to Submit a PR?

None

### ✅ Validations

- [x] Read the [docs](https://lobehub.com/zh/docs).
- [x] Check that there isn't [already an issue](https://github.com/lobehub/lobe-chat/issues) that reports the same bug to avoid creating a duplicate.
- [x] Make sure this is a LobeChat issue and not a third-party library or provider issue.
- [x] Check that this is a concrete bug. For Q&A, please use [GitHub Discussions](https://github.com/lobehub/lobe-chat/discussions) or join our [Discord Server](https://discord.gg/rGHwKq4R).

### PR DESCRIPTION
**Pull request by sxjeru**
… models

🔤 fix(clerk): update translation for password to通行密钥

#### 💻 Change Type

- [ ] ✨ feat
- [x] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 👷 build
- [ ] ⚡️ perf
- [ ] ✅ test
- [ ] 📝 docs
- [ ] 🔨 chore

#### 🔀 Description of Change

- 完善 #9530
- fix #10522

批量禁用启用模型，模型 type 参数不丢失。

#### 🧪 How to Test

- [ ] Tested locally
- [x] Added/updated tests
- [ ] No tests needed

#### 📸 Screenshots / Videos

| Before | After |
| ------ | ----- |
| ...    | ...   |

## Summary by Sourcery

Preserve type information for AI models during batch insert/update, add corresponding tests, and update the clerk locale translation.

Bug Fixes:
- Ensure model type is preserved when batch inserting or updating AI models by referencing the default model list

Documentation:
- Update the clerk locale translation for the password section title to '通行密钥'

Tests:
- Add a test to verify that disabling all models in a batch operation retains each model’s type

### CODE REVIEW

File: packages/database/src/models/aiModel.ts [hunk 1]
```diff
@@ -209,16 +223,30 @@ export class AiModelModel {
...
-        .set({ enabled })
-        .where(
-          and(
-            eq(aiModels.providerId, providerId),
-            inArray(aiModels.id, recordsToUpdate),
-            eq(aiModels.userId, this.userId),
-          ),
-        );
+      // Update each model individually to preserve type information
+      for (const modelId of recordsToUpdate) {
```
Comment (arvinxx) [inline packages/database/src/models/aiModel.ts]: 这个实现不行，会导致更新耗时很大。再改改实现

Comment (sxjeru) [reply packages/database/src/models/aiModel.ts]: 改了一下，串行改一次批量请求了。测试有提升
