### PR TITLE
🐛 fix:  unable to toggle SiliconCloud model thinking mode

### LINKED ISSUE #10009: SiliconFlow's all reasoning models are using new unified thinking parameters
### 📱 Client Type

Web (Desktop Browser), Desktop App (Electron)

### 💻 Operating System

Windows

### 📦 Deployment Platform

Vercel

### 🔧 Deployment Mode

client pgelite db (lobe-chat-pglite image)

### 📌 Version

v1.142.9

### 🌐 Browser

Firefox

### 🐛 Bug Description

Currently, SiliconFlow has updated the parameters for all reasoning models and unified them. All reasoning models now use the same set of parameters. The old parameter passing method is no longer in use, and multiple models have been affected.

### 📷 Recurrence Steps

When using the glm-4.6 model provided by SiliconFlow for dialogue (with reasoning enabled)

### 🚦 Expected Behavior

The model should perform reasoning normally

### 📝 Additional Information

https://docs.siliconflow.cn/cn/api-reference/chat-completions/chat-completions

### 🛠️ Willing to Submit a PR?

None

### ✅ Validations

- [x] Read the [docs](https://lobehub.com/zh/docs).
- [x] Check that there isn't [already an issue](https://github.com/lobehub/lobe-chat/issues) that reports the same bug to avoid creating a duplicate.
- [x] Make sure this is a LobeChat issue and not a third-party library or provider issue.
- [x] Check that this is a concrete bug. For Q&A, please use [GitHub Discussions](https://github.com/lobehub/lobe-chat/discussions) or join our [Discord Server](https://discord.gg/rGHwKq4R).

---
> This issue was translated by Claude.

<details>
<summary>Original Content</summary>

### 📱 Client Type

Web (Desktop Browser), Desktop App (Electron)

### 💻 Operating System

Windows

### 📦 Deployment Platform

Vercel

### 🔧 Deployment Mode

client pgelite db (lobe-chat-pglite image)

### 📌 Version

v1.142.9

### 🌐 Browser

Firefox

### 🐛 Bug Description

目前硅基流动(siliconflow)对所有的思考模型参数进行了更新,并且进行了统一,所有的思考模型使用同一套参数,老的传参方式已经不再使用,目前已有多款模型受到影响

### 📷 Recurrence Steps

在使用硅基流动提供的glm-4.6进行对话(开启思考)

### 🚦 Expected Behavior

模型正常思考

### 📝 Additional Information

https://docs.siliconflow.cn/cn/api-reference/chat-completions/chat-completions

### 🛠️ Willing to Submit a PR?

None

### ✅ Validations

- [x] Read the [docs](https://lobehub.com/zh/docs).
- [x] Check that there isn't [already an issue](https://github.com/lobehub/lobe-chat/issues) that reports the same bug to avoid creating a duplicate.
- [x] Make sure this is a LobeChat issue and not a third-party library or provider issue.
- [x] Check that this is a concrete bug. For Q&A, please use [GitHub Discussions](https://github.com/lobehub/lobe-chat/discussions) or join our [Discord Server](https://discord.gg/rGHwKq4R).

</details>

### LINKED ISSUE #12008: The thinking model of SiliconFlow cannot properly control thinking
### 📱 Client Type

Desktop App (Electron), Web (Mobile Browser), Web (Desktop Browser)

### 💻 Operating System

Windows

### 📦 Deployment Platform

Self hosting Docker

### 📌 Version

V2.0.9

### 🌐 Browser

Firefox

### 🐛 Bug Description

The thinking model of SiliconFlow cannot properly turn off thinking. As shown in the images below, it's not possible to properly turn off thinking.

Image

Image

Image

Image

### 📷 Recurrence Steps

Correctly configured, turn off thinking dialogue and start conversation

### 🚦 Expected Behavior

Correctly control whether to think or not

### 📝 Additional Information

_No response_

### 🛠️ Willing to Submit a PR?

None

### ✅ Validations

- [x] Read the [docs](https://lobehub.com/zh/docs).
- [x] Check that there isn't [already an issue](https://github.com/lobehub/lobe-chat/issues) that reports the same bug to avoid creating a duplicate.
- [x] Make sure this is a LobeChat issue and not a third-party library or provider issue.
- [x] Check that this is a concrete bug. For Q&A, please use [GitHub Discussions](https://github.com/lobehub/lobe-chat/discussions) or join our [Discord Server](https://discord.gg/rGHwKq4R).

---
> This issue was translated by Claude.

<details>
<summary>Original Content</summary>

### 📱 Client Type

Desktop App (Electron), Web (Mobile Browser), Web (Desktop Browser)

### 💻 Operating System

Windows

### 📦 Deployment Platform

Self hosting Docker

### 📌 Version

V2.0.9

### 🌐 Browser

Firefox

### 🐛 Bug Description

硅基流动的思考模型无法正常的关闭思考,如下图所示,无法正常的关闭思考

Image

Image

Image

Image

### 📷 Recurrence Steps

正确设置,关闭思考对话并对话

### 🚦 Expected Behavior

正确的控制是否思考

### 📝 Additional Information

_No response_

### 🛠️ Willing to Submit a PR?

None

### ✅ Validations

- [x] Read the [docs](https://lobehub.com/zh/docs).
- [x] Check that there isn't [already an issue](https://github.com/lobehub/lobe-chat/issues) that reports the same bug to avoid creating a duplicate.
- [x] Make sure this is a LobeChat issue and not a third-party library or provider issue.
- [x] Check that this is a concrete bug. For Q&A, please use [GitHub Discussions](https://github.com/lobehub/lobe-chat/discussions) or join our [Discord Server](https://discord.gg/rGHwKq4R).

</details>

### PR DESCRIPTION
**Pull request by sxjeru**
#### 💻 Change Type

- [ ] ✨ feat
- [x] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 👷 build
- [ ] ⚡️ perf
- [ ] ✅ test
- [ ] 📝 docs
- [ ] 🔨 chore

#### 🔗 Related Issue

- fix #10009
- close #12008

#### 🔀 Description of Change

测试可用。仅启用 `reasoningBudgetToken` 时将不再传递 thinking.type 参数。

另优化 SiliconCloud 错误显示，可正确显示报错信息。（图中下半）

image

#### 🧪 How to Test

- [x] Tested locally
- [ ] Added/updated tests
- [ ] No tests needed

#### 📸 Screenshots / Videos

| Before | After |
| ------ | ----- |
| ...    | ...   |

## Summary by Sourcery

Clean up deprecated Vercel AI chat models, introduce the Qwen Image Edit Plus model, and fix and enhance thinking mode support and budget constraints for SiliconCloud models.

New Features:
- Add Qwen Image Edit Plus image editing model

Bug Fixes:
- Fix toggling of thinking mode on SiliconCloud models

Enhancements:
- Remove deprecated chat models from the Vercel AI Gateway list
- Enforce a minimum thinking_budget of 128 tokens for SiliconCloud

### CODE REVIEW

File: packages/model-runtime/src/providers/anthropic/index.ts [hunk 1]
```diff
@@ -239,10 +239,10 @@ export class LobeAnthropicAI implements LobeRuntimeAI {
         model,
         system: systemPrompts,
         thinking: {
-          ...thinking,
-          budget_tokens: thinking?.budget_tokens
+          budget_tokens: thinking.budget_tokens
             ? Math.min(thinking.budget_tokens, maxTokens - 1) // `max_tokens` must be greater than `thinking.budget_tokens`.
             : 1024,
+          type: 'enabled',
```
Comment (arvinxx) [inline packages/model-runtime/src/providers/anthropic/index.ts]: 这里为啥加 enabled

Comment (sxjeru) [reply packages/model-runtime/src/providers/anthropic/index.ts]: 原本的 `...thinking` 不让过 lint，只能改成这样了，从 if 条件看应该没问题。
