### PR TITLE
🐛 fix: fix page not switch when clicking on the pin assistant

### LINKED ISSUE #4519: [Bug] 在文件或者发现页面点击固定助手时没有反应
### 📦 Environment

Official Preview

### 📌 Version

latest

### 💻 Operating System

macOS

### 🌐 Browser

Chrome

### 🐛 Bug Description

在文件或者发现页面点击固定助手时没有反应，正常应该切换到点击的助手

### 📷 Recurrence Steps

https://github.com/user-attachments/assets/cc1c96be-44a8-47c3-8cc7-2cf76c37396d

### 🚦 Expected Behavior

_No response_

### 📝 Additional Information

_No response_

### PR DESCRIPTION
**Pull request by mushan0x0**
#### 💻 变更类型 | Change Type

- [ ] ✨ feat
- [x] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 👷 build
- [ ] ⚡️ perf
- [ ] 📝 docs
- [ ] 🔨 chore

#### 🔀 变更说明 | Description of Change

close: #4519

#### 📝 补充信息 | Additional Information

修复后的样子

https://github.com/user-attachments/assets/3a9122fe-30a1-491c-b031-047b3456ba1f

### CODE REVIEW

File: src/app/(main)/@nav/_layout/Desktop/PinList/index.tsx [hunk 1]
```diff
@@ -6,6 +6,7 @@ import { parseAsBoolean, useQueryState } from 'nuqs';
 import { useHotkeys } from 'react-hotkeys-hook';
 import { Flexbox } from 'react-layout-kit';
 
+import { useSwitchSession } from '@/app/(main)/chat/@session/features/SessionListContent/useSwitchSession';
```
Comment (arvinxx) [inline src/app/(main)/@nav/_layout/Desktop/PinList/index.tsx]: `useSwitchSession` 已经被跨页面复用，可以挪到 `src/hooks` 下面了。

File: src/app/(main)/chat/@session/features/SessionListContent/useSwitchSession.ts [hunk 2]
```diff
@@ -10,15 +11,18 @@ export const useSwitchSession = () => {
   const togglePortal = useChatStore((s) => s.togglePortal);
   const mobile = useServerConfigStore((s) => s.isMobile);
   const router = useQueryRoute();
+  const pathname = usePathname();
 
   return useCallback(
     (id: string) => {
       switchSession(id);
       togglePortal(false);
+      console.log(pathname);
```
Comment (arvinxx) [inline src/app/(main)/chat/@session/features/SessionListContent/useSwitchSession.ts]: 清理下

**Review by arvinxx — APPROVED** [review]
LGTM, Thanks for your contribution!
