### PR TITLE
🐛 fix: Correctly pass `reasoning.summary`

### LINKED ISSUE #8214: o3 不支持 summary 思考过程
### 📦 部署环境

Docker

### 📦 部署模式

客户端 Pglite 模式(lobe-chat-pglite 镜像)

### 📌 软件版本

v1.94.11

### 💻 系统环境

macOS

### 🌐 浏览器

Chrome

### 🐛 问题描述

o3 调用时没有注入 summary 参数以输出思考过程，官方是支持的

### 📷 复现步骤

_No response_

### 🚦 期望结果

_No response_

### 📝 补充信息

_No response_

### PR DESCRIPTION
**Pull request by sxjeru**
#### 💻 变更类型 | Change Type

- [ ] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 👷 build
- [ ] ⚡️ perf
- [ ] 📝 docs
- [ ] 🔨 chore

#### 🔀 变更说明 | Description of Change

- close #8214

## Summary by Sourcery

Bug Fixes:
- Preserve existing `reasoning` properties when applying `summary: 'auto'` in the OpenAI runtime

### CODE REVIEW

File: src/libs/model-runtime/openai/index.ts [hunk 1]
```diff
@@ -76,9 +77,9 @@ export const LobeOpenAI = createOpenAICompatibleRuntime({
 
       if (prunePrefixes.some((prefix) => model.startsWith(prefix))) {
         if (!payload.reasoning) {
-          payload.reasoning = { summary: 'auto' };
+          payload.reasoning = { summary: 'detailed' };
```
Comment (arvinxx) [inline src/libs/model-runtime/openai/index.ts]: 为啥改成 detailed 了？

Comment (sxjeru) [reply src/libs/model-runtime/openai/index.ts]: 看了一下文档，我改回 auto 好了，之前没理解清楚意思。
